stages:
  - build-doc

build-doc:
  stage: build-doc
  tags:
    - embedded
  image:
    name: pandoc/extra
    entrypoint: ["/bin/sh", "-c"]
  script:
    - mkdir public
    - pandoc --template eisvogel --output=public/software_requirements.pdf documentation/software_requirements.md
  artifacts:
    paths:
      - public
    when: always
