version: "3.8"

networks:
   default:
      external:
         name: syntheticnet

services:

  oidc-client:
    hostname: oidc-client
    container_name: oidc-client
    restart: always
    build: oidc-client/
    ports:
      - "3000:3000"
    volumes: 
      - ./oidc-client:/app

  oidc-provider:
    hostname: oidc-provider
    container_name: oidc-provider
    restart: always
    build: oidc-provider/
    environment:
      - AUTHLIB_INSECURE_TRANSPORT=1
      - FLASK_ENV=development
      - FLASK_DEBUG=true
    ports:
      - "5000:5000"
#    volumes: 
#      - ./oidc-provider:/app

#  flask_db:
#    container_name: flask_db
#    image: postgres:12
#    ports:
#      - "5432:5432"
#    environment:
#      - POSTGRES_PASSWORD=postgres
#      - POSTGRES_USER=postgres
#      - POSTGRES_DB=postgres
#    volumes:
#      - pgdata:/var/lib/postgresql/data

#volumes:
#  pgdata: {}