version: "3.8"

services:

  exchanger:
    hostname: exchanger
    container_name: exchanger
    restart: always
    build: oauth_server/
    environment:
      - FLASK_APP=app.py
    ports:
      - "5000:5000"
    volumes: 
      - ./oauth_server:/app
    networks:
      - default
