version: "3.8"

networks:
   default:
      external:
         name: syntheticnet

services:

  keycloak:
    image: quay.io/keycloak/keycloak:20.0.5
    hostname: keycloak
    container_name: keycloak
    restart: always
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin 
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: 
      - start-dev
      - --import-realm