name: Advanced Usage

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: create file list
        id: files_list
        run: |
          echo "Lorem ipsum" > lorem_1.md  # create two example files
          echo "dolor sit amet" > lorem_2.md
          mkdir documentation/output  # create output dir
          echo "files=$(printf '"%s" ' *.md)" > $GITHUB_OUTPUT
      - uses: docker://pandoc/latex:2.9
        with:
          args: --output=documentation/output/results.pdf ${{ steps.files_list.outputs.files }}
      - uses: actions/upload-artifact@v3
        with:
          name: output
          path: documentation/output